spring:
  datasource:
    url: jdbc:mysql://liko.site/pigeon?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: likui19930215Q
    driver-class-name: com.mysql.jdbc.Driver

  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: HTML5

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop